### ISSUE TITLE
Can someone please explain about the table?

### ISSUE THREAD

**Issue by Rpascar1** [learn-co-curriculum/programming-univbasics-2-if-end-statement#2]
Beth Urban 2 MINUTES AGO
Hm - I'm not sure why, exactly, the readme mentions a table - I think it's just saying that if you were to create a table with a column of different values for chance_of_rain and kept track of the outputs for each, you'd see how the output changes
User avatar
Beth Urban A MINUTE AGO
But as long as you understand that when chance_of_rain changes, the output will change according to the if/elsif/else statements, then I think you can move on! :wink:

**Comment by sgharms** [comment]
Apparently Learn was not rendering our table correctly because of formatting complexity. We've converted the table so that it should work fine, now.

In the github repo one can see the table in question: https://github.com/learn-co-curriculum/programming-univbasics-2-if-end-statement

Whereas in Learn it was represented as:

https://flatiron-staff.slack.com/files/U8ETZJZ0U/FMBJ7TM6J/image.png

Should be fixed now!

**Comment by Rpascar1** [comment]
Thanks for the update !
